# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [39]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,accuracy_score,balanced_accuracy_score, precision_score,recall_score,f1_score,confusion_matrix
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split

## Regression Model Evaluation

In [40]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [3]:
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [41]:
# Your code here :
X = data.drop(columns=['MEDV'])
y = data['MEDV']

X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [42]:
# Your code here :
model = LinearRegression().fit(X_train,y_train)

# Generating the prediciton for train and test sets
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [43]:
# Your code here :
r2_train = r2_score(y_train,train_pred)
r2_test = r2_score(y_test,test_pred)

print(f'Train R2 score: {r2_train:.3f}')
print(f'Test R2 score: {r2_test:.3f}')

Train R2 score: 0.751
Test R2 score: 0.669

## 4. Calculate and print mean squared error for both the training and the testing set.

In [44]:
# Your code here :
mse_train = mean_squared_error(y_train,train_pred)
mse_test = mean_squared_error(y_test,test_pred)

print(f'Train MSE: {mse_train:.3f}')
print(f'Test MSE: {mse_test:.3f}')

Train MSE: 21.641
Test MSE: 24.291

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [45]:
# Your code here :
mae_train = mean_absolute_error(y_train,train_pred)
mae_test = mean_absolute_error(y_test,test_pred)

print(f'Train MAE: {mae_train:.3f}')
print(f'Test MAE: {mae_test:.3f}')

Train MAE: 3.315
Test MAE: 3.189

## Classification Model Evaluation

In [46]:
from sklearn.datasets import load_iris
data = load_iris()

In [13]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [47]:
column_names = data.feature_names

In [48]:
df = pd.DataFrame(data['data'],columns=column_names)

In [16]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [49]:
target = pd.DataFrame(data.target)

In [18]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [19]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [69]:
# Your code here :
X2 = df
y2 = target

X_train2, X_test2, y_train2,y_test2 = train_test_split(X2,y2,test_size=0.2, random_state=42)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [51]:
# Your code here :
model2 = LogisticRegression().fit(X_train2,y_train2)

train_pred2 = model2.predict(X_train2)
test_pred2 = model2.predict(X_test2)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [52]:
# Your code here :
train_accuracy = accuracy_score(y_train2,train_pred2)
test_accuracy = accuracy_score(y_test2,test_pred2)

print(f'Train Accuracy Score: {train_accuracy:.2f}')
print(f'Test Accuracy Score: {test_accuracy:.2f}')

Train Accuracy Score: 0.97
Test Accuracy Score: 1.00

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [53]:
# Your code here :
train_balanced_accuracy = balanced_accuracy_score(y_train2,train_pred2)
test_balanced_accuracy = balanced_accuracy_score(y_test2,test_pred2)

print(f'Train Balanced Accuracy Score: {train_balanced_accuracy:.2f}')
print(f'Test Balanced Accuracy Score: {test_balanced_accuracy:.2f}')

Train Balanced Accuracy Score: 0.98
Test Balanced Accuracy Score: 1.00

## 10. Calculate and print the precision score for both the training and the testing set.

In [54]:
# Your code here :
train_precision = precision_score(y_train2,train_pred2,average='macro')
test_precision = precision_score(y_test2,test_pred2, average='macro')

print(f'Train Precision Score: {train_precision:.2f}')
print(f'Test Precision Score: {test_precision:.2f}')

Train Precision Score: 0.98
Test Precision Score: 1.00

## 11. Calculate and print the recall score for both the training and the testing set.

In [55]:
# Your code here :
train_recall = recall_score(y_train2,train_pred2,average='macro')
test_recall = recall_score(y_test2,test_pred2, average='macro')

print(f'Train Recall Score: {train_recall:.2f}')
print(f'Test Recall Score: {test_recall:.2f}')

Train Recall Score: 0.98
Test Recall Score: 1.00

## 12. Calculate and print the F1 score for both the training and the testing set.

In [56]:
# Your code here :
train_f1 = f1_score(y_train2,train_pred2,average='macro')
test_f1 = f1_score(y_test2,test_pred2, average='macro')

print(f'Train F1 Score: {train_f1:.2f}')
print(f'Test F1 Score: {test_f1:.2f}')

Train F1 Score: 0.97
Test F1 Score: 1.00

## 13. Generate confusion matrices for both the training and the testing set.

In [62]:
# Your code here :
train_matrix = confusion_matrix(y_train2,train_pred2)
test_matrix = confusion_matrix(y_test2,test_pred2)
print("Train Confusion Matrix \n---------------\n", confusion_matrix(y_train2,train_pred2))
print('')
print("Test Confusion Matrix \n---------------\n", confusion_matrix(y_test2,test_pred2))

Train Confusion Matrix
---------------
 [[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]

Test Confusion Matrix
---------------
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [ ]:
# I will try different splits for each dataset

# 1 Housing 70/30

X_train70, X_test70,y_train70,y_test70 = train_test_split(X,y,test_size=0.3, random_state=42)

model70 = LinearRegression().fit(X_train70,y_train70)
train_pred70 = model.predict(X_train70)
test_pred70 = model.predict(X_test70)

r2_train70 = r2_score(y_train70,train_pred70)
r2_test70 = r2_score(y_test70,test_pred70)
mse_train70 = mean_squared_error(y_train70,train_pred70)
mse_test70 = mean_squared_error(y_test70,test_pred70)
mae_train70 = mean_absolute_error(y_train70,train_pred70)
mae_test70 = mean_absolute_error(y_test70,test_pred70)


# 2 Housing with 90/10

X_train90, X_test90,y_train90,y_test90 = train_test_split(X,y,test_size=0.1, random_state=42)

model90 = LinearRegression().fit(X_train90,y_train90)
train_pred90 = model.predict(X_train90)
test_pred90 = model.predict(X_test90)

r2_train90 = r2_score(y_train90,train_pred90)
r2_test90 = r2_score(y_test90,test_pred90)
mse_train90 = mean_squared_error(y_train90,train_pred90)
mse_test90 = mean_squared_error(y_test90,test_pred90)
mae_train90 = mean_absolute_error(y_train90,train_pred90)
mae_test90 = mean_absolute_error(y_test90,test_pred90)

In [67]:
# Gathering all for the different Splits
comparison = pd.DataFrame({'Split': [70,80,90],
              'R2 Train Set': [r2_train70, r2_train, r2_train90],
              'R2 Test Set': [r2_test70,r2_test, r2_test90],
              'MSE Train Set': [mse_train70, mse_train, mse_train90],
              'MSE Test Set': [mse_test70, mse_test, mse_test90],
              'MAE Train Set': [mae_train70, mae_train, mae_train90],
              'MAE Test Set': [mae_test70, mae_test, mae_test90],              
              })
comparison = comparison.set_index('Split')
comparison = round(comparison,3).T
comparison

Split              70      80      90
R2 Train Set    0.742   0.751   0.735
R2 Test Set     0.719   0.669   0.754
MSE Train Set  22.706  21.641  22.943
MSE Test Set   20.940  24.291  15.330
MAE Train Set   3.381   3.315   3.339
MAE Test Set    3.076   3.189   2.851

We can see that changing the train/test split ratios has a direct effect on the main metrics (R2, MSE and MAE) for both sets. However, the changes are not very large, suggesting some stability of the models between the splits.

The train R2 score increases between the 70 and 80 split for the train set but decreases for the 90 split. On the contrary, the test R2 score is the highest for the 90 split. Such variation is explained by the size increase of the train set (and reduction of the test set) which gives more data for the model to be fit upon.

In both the 70 and 80 splits R2(train) > R2(test) which would suggest a very minute overfitting. The opposite is observed for the 90 split.
The MSE and MAE are the lowest for the 90 split.

These major differences tend to show that the best split is the 90/10 split.

In [70]:
# 3 Iris plant 70/30
X_train270, X_test270, y_train270,y_test270 = train_test_split(X2,y2,test_size=0.3, random_state=42)
model270 = LogisticRegression().fit(X_train270,y_train270)

train_pred270 = model270.predict(X_train270)
test_pred270 = model270.predict(X_test270)

train_accuracy70 = accuracy_score(y_train270,train_pred270)
test_accuracy70 = accuracy_score(y_test270,test_pred270)
train_balanced_accuracy70 = balanced_accuracy_score(y_train270,train_pred270)
test_balanced_accuracy70 = balanced_accuracy_score(y_test270,test_pred270)
train_precision70 = precision_score(y_train270,train_pred270,average='macro')
test_precision70 = precision_score(y_test270,test_pred270, average='macro')
train_recall70 = recall_score(y_train270,train_pred270,average='macro')
test_recall70 = recall_score(y_test270,test_pred270, average='macro')
train_f170 = f1_score(y_train270,train_pred270,average='macro')
test_f170 = f1_score(y_test270,test_pred270, average='macro')
train_matrix70 = confusion_matrix(y_train270,train_pred270)
test_matrix70 = confusion_matrix(y_test270,test_pred270)

# 4 Iris plant 90/10
X_train290, X_test290, y_train290,y_test290 = train_test_split(X2,y2,test_size=0.1, random_state=42)
model290 = LogisticRegression().fit(X_train290,y_train290)

train_pred290 = model290.predict(X_train290)
test_pred290 = model290.predict(X_test290)

train_accuracy90 = accuracy_score(y_train290,train_pred290)
test_accuracy90 = accuracy_score(y_test290,test_pred290)
train_balanced_accuracy90 = balanced_accuracy_score(y_train290,train_pred290)
test_balanced_accuracy90 = balanced_accuracy_score(y_test290,test_pred290)
train_precision90 = precision_score(y_train290,train_pred290,average='macro')
test_precision90 = precision_score(y_test290,test_pred290, average='macro')
train_recall90 = recall_score(y_train290,train_pred290,average='macro')
test_recall90 = recall_score(y_test290,test_pred290, average='macro')
train_f190 = f1_score(y_train290,train_pred290,average='macro')
test_f190 = f1_score(y_test290,test_pred290, average='macro')
train_matrix90 = confusion_matrix(y_train290,train_pred290)
test_matrix90 = confusion_matrix(y_test290,test_pred290)

In [71]:
# Gathering all for the different Splits
comparison2 = pd.DataFrame({'Split': [70,80,90],
              'Train Accuracy': [train_accuracy70, train_accuracy, train_accuracy90],
              'Test Accuracy': [test_accuracy70,test_accuracy, test_accuracy90],
              'Train Balanced Accuracy': [train_balanced_accuracy70, train_balanced_accuracy, train_balanced_accuracy90],
              'Test Balanced Accuracy': [test_balanced_accuracy70, test_balanced_accuracy, test_balanced_accuracy90],
              'Train Precision': [train_precision70, train_precision, train_precision90],
              'Test Precision': [test_precision70, test_precision, test_precision90],
              'Train Recall': [train_recall70,train_recall,train_recall90],
              'Test Recall': [test_recall70,test_recall,test_recall90],
              'Train F1 Score': [train_f170,train_f1,train_f190],
              'Test F1 Score': [test_f170,test_f1,test_f190],          
              })
comparison2 = comparison2.set_index('Split')
comparison2 = round(comparison2,3).T
comparison2

Split                       70     80     90
Train Accuracy           0.962  0.975  0.978
Test Accuracy            1.000  1.000  1.000
Train Balanced Accuracy  0.964  0.976  0.977
Test Balanced Accuracy   1.000  1.000  1.000
Train Precision          0.965  0.976  0.980
Test Precision           1.000  1.000  1.000
Train Recall             0.964  0.976  0.977
Test Recall              1.000  1.000  1.000
Train F1 Score           0.964  0.975  0.978
Test F1 Score            1.000  1.000  1.000

Although all test results point to perfected predictions (all scores = 1) regardless of the test size, we can attribute this to the nature of the dataset. 

The interesting thing to notice is the evolution of the train set results with its increase in size. All criteria increase when increasing the size of the train set, the 90 split shows the highest values for all criteria such as Precision, F1 score, Accuracy ... We expect such trend since we give more and more data into the trazining set leading to a better fitted model.